# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-05 06:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_auto_20170705_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='mobile',
            field=models.CharField(default='', max_length=10),
        ),
    ]
